artifacts_root: artifacts

data_ingestion:
  root_dir: articats/data_ingestion
  source_url: https://drive.google.com/file/d/1G6hn9Y7CubAFMHQPOLcdmoXAUrJgPplU/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: articats/data_ingestion